// Semantic colour tokens, one per Figma semantic style (Background/*, Border/*, Text & icon/*, CTA/*).
// `default` = Figma "Light/…", `_dark` = Figma "Dark/…". Values reference primitives from foundations/colors.ts
// by path. Where Figma's semantic style carries a hex that exists in no primitive of that mode, the raw hex is
// kept verbatim (decision D9: fidelity to Figma) and flagged with `// no Figma primitive`.
// Cross-reference generated by `node scripts/figma-to-tokens.mjs`.
// NOTE: the CTA state Figma calls "default" is named `base` here — `default` is the reserved
// light-mode condition key inside a Chakra semantic token value and cannot also be a token name.
export const semanticTokens = {
  colors: {
    bg: {
      primary: { default: 'light.light.primary', _dark: '#171D26' }, // no Figma primitive (dark)
      secondary: { default: '#F8FAFC', _dark: '#171D26' }, // no Figma primitive (light, dark)
      tertiary: { default: '#F1F5F9', _dark: 'dark.gray.quaternary' }, // no Figma primitive (light)
      disabled: { default: '#F4F5F6', _dark: 'dark.neutral.quaternary' }, // no Figma primitive (light)
      info: { default: 'light.blue.quaternary', _dark: 'dark.blue.tertiary' },
      success: { default: 'light.green.quaternary', _dark: 'dark.green.tertiary' },
      attention: { default: 'light.yellow.quaternary', _dark: 'dark.yellow.tertiary' },
      critical: { default: 'light.red.quaternary', _dark: 'dark.red.tertiary' },
    },
    border: {
      regular: { default: '#72777E', _dark: '#D6D8DB' }, // no Figma primitive (light, dark)
      subdue: { default: 'light.neutral.quaternary', _dark: 'dark.neutral.tertiary' },
      brand: { default: 'light.indigo.primary', _dark: '#AEA9FE' }, // no Figma primitive (dark)
      disabled: { default: 'light.neutral.quaternary', _dark: 'dark.neutral.tertiary' },
      critical: { default: 'light.red.primary', _dark: 'dark.red.primary' },
      success: { default: 'light.green.primary', _dark: '#76C643' }, // no Figma primitive (dark)
      attention: { default: 'light.yellow.primary', _dark: 'dark.yellow.primary' },
    },
    text: {
      primary: { default: '#1D1E20', _dark: 'dark.light.primary' }, // no Figma primitive (light)
      primaryInverse: { default: 'light.light.primary', _dark: '#1D1E20' }, // no Figma primitive (dark)
      subdue: { default: '#72777E', _dark: '#BBBFC4' }, // no Figma primitive (light, dark)
      disabled: { default: 'light.neutral.secondary', _dark: 'dark.neutral.tertiary' },
      critical: { default: 'light.red.primary', _dark: 'dark.red.primary' },
      attention: { default: 'light.yellow.primary', _dark: 'dark.yellow.primary' },
      success: { default: 'light.green.primary', _dark: '#76C643' }, // no Figma primitive (dark)
      link: { default: '#4837B9', _dark: '#AEA9FE' }, // no Figma primitive (light, dark)
      brand: { default: 'light.indigo.primary', _dark: 'dark.indigo.primary' },
    },
    cta: {
      primary: {
        base: { default: '#4837B9', _dark: 'dark.indigo.tertiary' }, // Figma: default · no Figma primitive (light)
        hover: { default: 'light.indigo.secondary', _dark: 'dark.indigo.secondary' },
        pressed: { default: 'light.indigo.primary', _dark: 'dark.indigo.quaternary' },
      },
      secondary: {
        base: { default: 'light.light.primary', _dark: '#171D26' }, // Figma: default · no Figma primitive (dark)
        hover: { default: '#F5F5FF', _dark: 'dark.dark.secondary' }, // no Figma primitive (light)
        pressed: { default: 'light.indigo.quaternary', _dark: 'dark.indigo.quaternary' },
      },
      tertiary: {
        base: { default: 'light.light.primary', _dark: '#171D26' }, // Figma: default · no Figma primitive (dark)
        hover: { default: '#F5F5FF', _dark: 'dark.dark.secondary' }, // no Figma primitive (light)
        pressed: { default: 'light.indigo.quaternary', _dark: 'dark.indigo.quaternary' },
      },
    },
  },
};
